In [ ]:
import pandas as pd # Preprocessing, read csv, etc
import numpy as np #For linear algebra

In [62]:
# Filtering data from 10001 to 15000 (5000 data)
df = pd.read_csv(r".\host_train.csv", skiprows=range(1, 10001), nrows=5000)
display(df)

,case_id,Hospital,Hospital_type,Hospital_city,Hospital_region,Available_Extra_Rooms_in_Hospital,Department,Ward_Type,Ward_Facility,Bed_Grade,patientid,City_Code_Patient,Type of Admission,Illness_Severity,Patient_Visitors,Age,Admission_Deposit,Stay_Days
0,10001,29,0,4,0,3,gynecology,R,F,3.0,47321,2.0,Trauma,Minor,3,41-50,4660.0,11-20
1,10002,6,0,6,0,3,gynecology,R,F,3.0,47321,2.0,Trauma,Minor,3,41-50,5333.0,21-30
2,10003,11,1,2,1,3,gynecology,Q,D,2.0,47321,2.0,Trauma,Minor,3,41-50,6095.0,21-30
3,10004,6,0,6,0,3,gynecology,R,F,3.0,47321,2.0,Urgent,Minor,3,41-50,3962.0,11-20
4,10005,7,0,4,0,3,TB & Chest disease,R,F,3.0,47321,2.0,Urgent,Minor,3,41-50,6437.0,11-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,32,5,9,1,2,gynecology,S,B,2.0,102707,8.0,Emergency,Extreme,6,51-60,4031.0,51-60
4996,14997,26,1,2,1,5,gynecology,P,D,2.0,102707,8.0,Emergency,Extreme,4,51-60,4277.0,21-30
4997,14998,11,1,2,1,4,gynecology,Q,D,2.0,102707,8.0,Trauma,Extreme,2,51-60,4459.0,11-20
4998,14999,19,0,7,1,2,gynecology,S,C,1.0,102707,8.0,Emergency,Extreme,8,51-60,3152.0,71-80
4999,15000,26,1,2,1,4,gynecology,P,D,1.0,102707,8.0,Emergency,Extreme,2,51-60,2533.0,61-70

In [61]:
df.dtypes # Showing atributes of data

case_id                                int64
Hospital                               int64
Hospital_type                          int64
Hospital_city                          int64
Hospital_region                        int64
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility                         object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type of Admission                     object
Illness_Severity                      object
Patient_Visitors                       int64
Age                                   object
Admission_Deposit                    float64
Stay_Days                             object
dtype: object